export {
  RuleConfigSchema,
  parseRuleConfig,
  OvertimeWhenSchema,
  OvertimeRoundingModeSchema,
  DEFAULT_OVERTIME_ROUNDING,
  DEFAULT_OVERTIME_MEAL_BREAK,
  DEFAULT_OVERTIME_DAILY_CAP_MINUTES,
  DEFAULT_OVERTIME_MONTHLY_ALERT_HOURS,
  DEFAULT_HOURLY_WAGE_DIVISOR,
  DEFAULT_REQUIRE_APPROVED_SHEET,
  DEFAULT_REQUIRE_ANOMALY_ACK,
  resolveOvertimeRounding,
  resolveOvertimeMealBreak,
  resolveOvertimeDailyCapMinutes,
  resolveOvertimeMonthlyAlertHours,
  resolveHourlyWageDivisor,
  resolvePayrollGates,
  resolveLateEarlyDeductionEnabled,
  // 2026-09-23 需求補齊:加班上限/起算基準/特休週年制/勞健保級距
  OvertimeBasisSchema,
  OvertimeBeyondCapSchema,
  AnnualLeaveBasisSchema,
  DEFAULT_OVERTIME_BASIS,
  DEFAULT_OVERTIME_MONTHLY_CAP_HOURS,
  DEFAULT_OVERTIME_BEYOND_CAP,
  DEFAULT_ANNUAL_LEAVE_BASIS,
  DEFAULT_ANNUAL_LEAVE_TABLE,
  DEFAULT_ANNUAL_LEAVE_INCREMENT,
  DEFAULT_ANNUAL_LEAVE_TYPE_CODE,
  resolveOvertimeBasis,
  resolveOvertimeMonthlyCapHours,
  resolveOvertimeBeyondCap,
  resolveAnnualLeavePolicy,
  resolveInsuranceBrackets,
  bracketFor,
  type RuleConfig,
  type OvertimeWhen,
  type OvertimeRounding,
  type OvertimeRoundingMode,
  type OvertimeMealBreak,
  type OvertimeBasis,
  type OvertimeBeyondCap,
  type AnnualLeaveBasis,
  type AnnualLeaveTier,
  type AnnualLeaveIncrement,
  type AnnualLeavePolicy,
  type InsuranceBracketSet,
} from "./rules-schema.js";

export * from "./types.js";
export { computeAttendanceDay, applyOvertimePipeline } from "./worktime-engine.js";
export { computePayslip } from "./payroll-engine.js";
export {
  bonusSupplementaryPremium,
  otherIncomeSupplementaryPremium,
  salaryWithholdingFixedRate,
  nonResidentWithholding,
  nhiEmployeePremium,
  DEFAULT_SUPPLEMENTARY_NHI_RATE,
  BONUS_MULTIPLE_THRESHOLD,
  OTHER_INCOME_MIN,
  NHI_MAX_DEPENDENTS,
  PENSION_VOLUNTARY_RATE_MAX,
} from "./tw-tax.js";
