import { pgTable, uuid, text, date, timestamp, uniqueIndex } from "drizzle-orm/pg-core"
import { tenants } from "./tenants"

/**
 * Tenant calendar days — per-tenant overrides layered on top of the worktime
 * engine's default workweek: statutory holidays, a company-declared 補假/調整
 *放假 workday, an extra 公司內定 rest day, etc. `dayType` mirrors the engine's
 * DayType ('workday' | 'rest_day' | 'fixed_holiday'); enforced by a CHECK
 * constraint added in sql/0026 (drizzle has no first-class enum/CHECK here,
 * same reasoning as sql/0021's projects_status_chk). `label` is the human
 * name shown in the calendar UI (e.g. "端午節"). `source` distinguishes a
 * manually entered row from one imported (e.g. from the 行政院人事行政總處
 * 辦公日曆表) or generated by a rule; not DB-enforced, read by the UI to
 * decide whether a row is safe to bulk-overwrite on re-import. The unique
 * (tenant_id, date) index keeps exactly one ruling per calendar day.
 */
export const tenantCalendarDays = pgTable(
  "tenant_calendar_days",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    date: date("date").notNull(),
    dayType: text("day_type").notNull(),
    label: text("label"),
    source: text("source").notNull().default("manual"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    tenantDateUnique: uniqueIndex("tenant_calendar_days_tenant_date_uq").on(
      table.tenantId,
      table.date,
    ),
  }),
)
